project:
  type: website
  output-dir: docs

website:
  title: "Global_UTEN"
  favicon: archive/images/Logo_1.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - workshop.qmd
      - cities.qmd
     

format:
  html:
    page-layout: full
    theme: 
      - sketchy
      - custom.scss
    css: styles.css
    toc: true



