project:
  type: website
  output-dir: docs

website:
  title: "Website_UTEN"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - Workshop.qmd

format:
  html:
    theme: 
      - darkly
      - custom.scss
    css: styles.css
    toc: true



